// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqXrhg_yDoNG05giXOziSTYmtOxZT5Sjk',
    appId: '1:288453570407:web:e324a0bba104abc63c89c2',
    messagingSenderId: '288453570407',
    projectId: 'vivian-first-project-001',
    authDomain: 'vivian-first-project-001.firebaseapp.com',
    storageBucket: 'vivian-first-project-001.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO5kj072QQsKe0ihnCZjMDm-A0Y2neIUg',
    appId: '1:288453570407:android:3b720221b69cd3083c89c2',
    messagingSenderId: '288453570407',
    projectId: 'vivian-first-project-001',
    storageBucket: 'vivian-first-project-001.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDE93ZagHJSB22X0EhdXmo5fig2RENvkP0',
    appId: '1:288453570407:ios:2896055faf776dba3c89c2',
    messagingSenderId: '288453570407',
    projectId: 'vivian-first-project-001',
    storageBucket: 'vivian-first-project-001.appspot.com',
    iosClientId: '288453570407-iqmj80illdmfudrm5rhc8r9l5u1sjth9.apps.googleusercontent.com',
    iosBundleId: 'com.vivianfirstproject',
  );
}
